/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _4AHME.ue07.gui;

import java.util.*;
import javax.swing.JOptionPane;
import _4AHME.ue07.calc.StatistikRechner;


/**
 *
 * @author micha
 */
public class BetterStatistikGUI extends javax.swing.JFrame {
     private final ArrayList<Double> zahlen = new ArrayList<>();
    /**
     * Creates new form BetterStatistik2
     */
    public BetterStatistikGUI() {
        
        initComponents();
        final DoubleListModel model = new DoubleListModel(zahlen);
        listenfeld.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pMain = new javax.swing.JPanel();
        pEast = new javax.swing.JPanel();
        pEingabe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfEingabe = new javax.swing.JFormattedTextField();
        pAusgabe = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfDurchschnitt = new javax.swing.JFormattedTextField();
        tfStdabw = new javax.swing.JFormattedTextField();
        pListe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listenfeld = new javax.swing.JList<>();
        pSouth = new javax.swing.JPanel();
        pButtons = new javax.swing.JPanel();
        btHinzufuegen = new javax.swing.JButton();
        btLoeschen = new javax.swing.JButton();
        btAllesLoeschen = new javax.swing.JButton();
        btBerechnen = new javax.swing.JButton();
        btBeenden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Statistik Rechner ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onWindowClosing(evt);
            }
        });

        pMain.setLayout(new java.awt.BorderLayout());

        pEast.setLayout(new java.awt.BorderLayout());

        pEingabe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Eingabe"));
        java.awt.GridBagLayout pEingabeLayout = new java.awt.GridBagLayout();
        pEingabeLayout.columnWidths = new int[] {0, 5, 0};
        pEingabeLayout.rowHeights = new int[] {0};
        pEingabe.setLayout(pEingabeLayout);

        jLabel1.setText("Zahl:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pEingabe.add(jLabel1, gridBagConstraints);

        tfEingabe.setColumns(10);
        tfEingabe.setValue(0.0);
        tfEingabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEingabeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        pEingabe.add(tfEingabe, gridBagConstraints);

        pEast.add(pEingabe, java.awt.BorderLayout.NORTH);

        pAusgabe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Ausgabe"));
        java.awt.GridBagLayout pAusgabeLayout = new java.awt.GridBagLayout();
        pAusgabeLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        pAusgabeLayout.rowHeights = new int[] {0, 5, 0};
        pAusgabe.setLayout(pAusgabeLayout);

        jLabel2.setText("Durchschnitt:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pAusgabe.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Standardabweichung: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pAusgabe.add(jLabel3, gridBagConstraints);

        tfDurchschnitt.setEditable(false);
        tfDurchschnitt.setColumns(10);
        tfDurchschnitt.setValue(0.0);
        tfDurchschnitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDurchschnittActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        pAusgabe.add(tfDurchschnitt, gridBagConstraints);

        tfStdabw.setEditable(false);
        tfStdabw.setColumns(10);
        tfStdabw.setValue(0.0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        pAusgabe.add(tfStdabw, gridBagConstraints);

        pEast.add(pAusgabe, java.awt.BorderLayout.SOUTH);

        pMain.add(pEast, java.awt.BorderLayout.EAST);

        pListe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Liste"));
        pListe.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(listenfeld);

        pListe.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pMain.add(pListe, java.awt.BorderLayout.CENTER);

        pButtons.setLayout(new java.awt.GridLayout(1, 0));
        pSouth.add(pButtons);

        btHinzufuegen.setText("Hinzufuegen");
        btHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHinzufuegenActionPerformed(evt);
            }
        });
        pSouth.add(btHinzufuegen);

        btLoeschen.setText("Löschen");
        btLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLoeschen(evt);
            }
        });
        pSouth.add(btLoeschen);

        btAllesLoeschen.setText("Alles Löschen");
        btAllesLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAllesLoeschen(evt);
            }
        });
        pSouth.add(btAllesLoeschen);

        btBerechnen.setText("Berechnen");
        btBerechnen.setToolTipText("");
        btBerechnen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBerechnen(evt);
            }
        });
        pSouth.add(btBerechnen);

        btBeenden.setText("Beenden");
        btBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBeenden(evt);
            }
        });
        pSouth.add(btBeenden);

        pMain.add(pSouth, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onLoeschen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLoeschen
       
        /*Einfache Lösung
        final int selIndex = listenfeld.getSelectedIndex(); // Wird das erste element markiert bekommt man null, bei mehreren -1
        if(selIndex < 0)
            JOptionPane.showMessageDialog(this,"Bitte eine Zahl selektieren",
                    "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
        
        else 
        
            if(JOptionPane.showConfirmDialog(this, "Sind Sie sicher, dass sie die selektierte Zahl löschen wollen.", "Sicherheitsabfrage", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
           
            zahlen.remove(selIndex);
            final DoubleListModel model = new DoubleListModel(zahlen);
             listenfeld.setModel(model);
        }*/
       final int[] sel = listenfeld.getSelectedIndices();
        if(sel.length==0)
        {
            JOptionPane.showMessageDialog(this, "Bitte erst eine Zahl selektieren!","Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
        }
        else
            if(JOptionPane.showConfirmDialog(this, String.format("Sind Sie sicher, dass Sie %d Zahlen löschen wollen?", sel.length), "Sicherheitsabfrage", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                for(int i = sel.length-1;i>=0;i--)
                    zahlen.remove(sel[i]);
                 final DoubleListModel model = new DoubleListModel(zahlen); //neues Listenmodel erzeugen
                 listenfeld.setModel(model); //Listenmodel setzen
            }
    }//GEN-LAST:event_onLoeschen

    private void tfEingabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEingabeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEingabeActionPerformed

    private void tfDurchschnittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDurchschnittActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDurchschnittActionPerformed

    private void btHinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHinzufuegenActionPerformed
        final Double zahl= ((Number)tfEingabe.getValue()).doubleValue(); //Zahl aus Textfeld holen
        zahlen.add(zahl); // Zahl in Collection einfügen
        final DoubleListModel model = new DoubleListModel(zahlen); //neues Listenmodel erzeugen
        listenfeld.setModel(model); //Listenmodel setzen
    }//GEN-LAST:event_btHinzufuegenActionPerformed

    private void onBerechnen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBerechnen
        try
        {
            final StatistikRechner rechner = new StatistikRechner(zahlen);
            tfDurchschnitt.setValue(rechner.getDurchschnitt());
            tfStdabw.setValue(rechner.getStandardabweichung());
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_onBerechnen

    private void onAllesLoeschen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAllesLoeschen
        zahlen.clear();
        final DoubleListModel model = new DoubleListModel(zahlen);
        listenfeld.setModel(model);
    }//GEN-LAST:event_onAllesLoeschen

    private void onX()
    {
        if(JOptionPane.showConfirmDialog(this, "Wollen Sie wirklich beenden?", "Sicherheitsabfrage", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            dispose();
        }
    }
    private void onBeenden(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBeenden
        onX();
    }//GEN-LAST:event_onBeenden

    private void onWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClosing
        onX();
    }//GEN-LAST:event_onWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BetterStatistikGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BetterStatistikGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BetterStatistikGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BetterStatistikGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BetterStatistikGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAllesLoeschen;
    private javax.swing.JButton btBeenden;
    private javax.swing.JButton btBerechnen;
    private javax.swing.JButton btHinzufuegen;
    private javax.swing.JButton btLoeschen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Double> listenfeld;
    private javax.swing.JPanel pAusgabe;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pEast;
    private javax.swing.JPanel pEingabe;
    private javax.swing.JPanel pListe;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pSouth;
    private javax.swing.JFormattedTextField tfDurchschnitt;
    private javax.swing.JFormattedTextField tfEingabe;
    private javax.swing.JFormattedTextField tfStdabw;
    // End of variables declaration//GEN-END:variables
}
